name = "pastebin"
main = "src/worker.js"
compatibility_date = "2026-07-06"
kv_namespaces = [
  { binding = "KV", id = "YOUR_KV_NAMESPACE_ID" }
]
routes = [
  { pattern = "pb.zzdbilly.workers.dev", zone_id = "" }
]
